# Generated by Django 3.2.5 on 2021-07-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spypyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spypyapp.neighbor'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spypyapp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spypyapp.neighbor'),
        ),
    ]
