# Generated by Django 3.2.5 on 2021-07-25 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spypyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='head',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=60)),
                ('post_description', models.TextField(default='')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor', to='spypyapp.neighbor')),
            ],
        ),
    ]
