# Generated by Django 3.2.5 on 2021-07-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spypyapp', '0002_auto_20210726_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='neighborhood',
        ),
    ]
