# Generated by Django 3.2.5 on 2021-07-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spypyapp', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='health_contact',
            field=models.IntegerField(blank=True, default=717878813),
        ),
    ]
