# Generated by Django 3.2.5 on 2021-07-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spypyapp', '0006_auto_20210725_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='health_contact',
            field=models.IntegerField(blank=True, default=254717878813),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='police_contact',
            field=models.IntegerField(blank=True, default=999),
        ),
    ]
