# Generated by Django 3.2.5 on 2021-07-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spypyapp', '0008_auto_20210725_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
